### ISSUE TITLE
Is there a way to get the result points at the moment?

### ISSUE THREAD

**Issue by xLEpEX** [ChenjieXu/pyzxing#13]
I'm not sure if I'm worng, but is there a reason why i can´t get the resultpoints at the moment? Because it 
looks like `result['points'] = [ast.literal_eval(line[12:]) for line in lines[points_index+1:-1]]` it is not working

**Comment by ChenjieXu** [comment]
The result parser function has been updated in version 0.3.3 and I have not added point results in it. I will fix it in next release. Or you may install version 0.3.2 by using pip install pyzxing==0.3.2 for now.

**Comment by ChenjieXu** [comment]
Points info is included in the latest version.
