### ISSUE TITLE
For file format QR code.

### ISSUE THREAD

**Issue by 469312306** [ChenjieXu/pyzxing#16]
I made a simple wrapper to handle the file format QR code:
```python
def _decode(self, filename):
    try:
        # the origin code
        cmd = ' '.join([self.command, self.lib_path, 'file:///' + filename, '--multi'])
        (stdout, _) = subprocess.Popen(cmd,
                                        stdout=subprocess.PIPE,
                                        universal_newlines=True,
                                        shell=True).communicate()
        lines = stdout.splitlines()
        separator_idx = [
            i for i in range(len(lines)) if lines[i][:4] == 'file'
        ] + [len(lines)]

        result = [
            self._parse_single(lines[separator_idx[i]:separator_idx[i + 1]])
            for i in range(len(separator_idx) - 1)
        ]
    except:
        # my add-in code
        cmd = ' '.join([self.command, self.lib_path, 'file:///' + filename, '--multi'])
        (lines, _) = subprocess.Popen(cmd,
                                    stdout=subprocess.PIPE,
                                    stderr=subprocess.PIPE).communicate()
        result = lines[lines.index(b'Raw result:\n')+len(b'Raw result:\n'):lines.index(b'\nFound')]
    return result
```
This will return the 'Raw result' bytes while the result can't be decoded with the default character set.

**Comment by ChenjieXu** [comment]
I can't understand why I don't quite understand why you want to add this method? Under what circumstances will the raw result be returned? Could you please provide an example for me to test?

**Comment by 469312306** [comment]
You can try this QR code, the decode result should be a file in bytes' format.
![da](https://user-images.githubusercontent.com/25743419/109601216-61ea8f80-7b59-11eb-9886-ef16fe1e099f.png)

**Comment by 469312306** [comment]
With the circumstances that the decode result is not sentences(or in other words, the decode result can't be transform to the system default character set(gbk/utf-8/...)), the program will exit with error. In my opinion, with this situation,  it's better to output the raw bytes result, and for professional, they can handle the raw bytes result themselves.

**Comment by ChenjieXu** [comment]
Thank you for your reply. I will look into it.

**Comment by ChenjieXu** [comment]
I change everything into bytes. Please check the latest version.

**Comment by 469312306** [comment]
thank you for update!
