### ISSUE TITLE
recognition is slow on mac

### ISSUE THREAD

**Issue by zhaozhen1002** [ChenjieXu/pyzxing#17]
thanks for your great work!
when I ran pyzxing for one image and it cost more than **two seconds** on mac os.
Although multiple pictures parallel computing is very fast . (55pictures / 20s)

How much time do you spend on a single picture?
Is there something wrong with my environment?

**Comment by ChenjieXu** [comment]
According to your description, the problem may be that the Mac machine takes a lot of time to start the JVM virtual machine, so parallelism greatly improves the performance of the task.

I got such result on my server.
`python scanner.py -f src/resources/code128.png
Use local jar file.
Prepare  0.0003101825714111328
Decode  0.36128950119018555
8101054321120021123456
`

Here is my test code.
`import time
    start = time.time()
    reader = BarCodeReader()
    print("Prepare ", time.time()-start)
    start = time.time()
    results = reader.decode(args.file)
    print("Decode ", time.time()-start)`

**Comment by zhaozhen1002** [comment]
Thank you very much!
 I got 0.2s  for a single picture on ubuntu!

And another question is that I think pyzxing is only support read images but not np.array.
`results = reader.decode('/PATH/TO/FILES/*.png')`
How can i modify source code to make it support for np.arrary?
(Maybe impossible?)

**Comment by ChenjieXu** [comment]
This is because the back-end mechanism, pyzxing calls zxing to read the image in background, so array can not be explicitly passed for decoding. So I suggest you save the array into a picture in temp folder, and then use pyzxing to decode it.
It is a good feature. I may support decoding np.array in the next release.

**Comment by zhaozhen1002** [comment]
Thanks!

> I may support decoding np.array in the next release.
I am looking forward to it! Thank you!

**Comment by ChenjieXu** [comment]
Good news!  Decoding np.array using reader.decode_array is supported in the latest release. Have fun with it!

**Comment by zhaozhen1002** [comment]
very thankful!!!

**Comment by zhaozhen1002** [comment]
Hi , I have tried pyzxing0.3.5 and it's very good! Thanks!
But it seems there are some little errors in it.
When i used [[maxicode]](https://github.com/zxing/zxing/tree/master/core/src/test/resources/blackbox/maxicode-1) picture for test, both of decode[array] and decode [filename], will get this error.
![image](https://user-images.githubusercontent.com/48865673/110580641-6db70100-81ac-11eb-8c43-2e5833cd21a5.png)

But pyzxing0.3.4 can recognize maxicode successfully!

**Comment by zhaozhen1002** [comment]
And when using decode[array], a hidden folder 「.cache」 will be created, but it will not be deleted automatically, which may also be a little problem when used for a long time.

**Comment by ChenjieXu** [comment]
> Hi , I have tried pyzxing0.3.5 and it's very good! Thanks!
> But it seems there are some little errors in it.
> When i used [[maxicode]](https://github.com/zxing/zxing/tree/master/core/src/test/resources/blackbox/maxicode-1) picture for test, both of decode[array] and decode [filename], will get this error.
> ![image](https://user-images.githubusercontent.com/48865673/110580641-6db70100-81ac-11eb-8c43-2e5833cd21a5.png)
> 
> But pyzxing0.3.3 can recognize maxicode successfully! (0.3.4 also❌ )

I open a new issue for this problem

**Comment by ChenjieXu** [comment]
> And when using decode[array], a hidden folder 「.cache」 will be created, but it will not be deleted automatically, which may also be a little problem when used for a long time.

Sorry for the inconvenience. I fix this in the latest commit but I haven't publish a new release. Please try install from source using python setup.py install command.
