### ISSUE TITLE
条码识别性能问题

### ISSUE THREAD

**Issue by LeileiCao** [ChenjieXu/pyzxing#22]
作者您好，我发现有些条码pyzxing无法识别,但zxing的online版本可以识别出来，不知为啥。

**Comment by ChenjieXu** [comment]
你是用的是pyzxing预置的zxing的jar包吗？可以尝试进入zxing的文件夹编译最新的版本的jar包。

**Comment by ChenjieXu** [comment]
你是否能提供一些例子以供我测试？谢谢

**Comment by LeileiCao** [comment]
> 你是否能提供一些例子以供我测试？谢谢

![temp](https://user-images.githubusercontent.com/39022261/114146836-a5030400-994a-11eb-9d94-1e0e8fcadd68.jpg)

**Comment by LeileiCao** [comment]
> 你是用的是pyzxing预置的zxing的jar包吗？可以尝试进入zxing的文件夹编译最新的版本的jar包。

我直接pip install pyzxing安装的。

**Comment by ChenjieXu** [comment]
我从最新的zxing库编译javase-3.4.2-jar-with-dependencies.jar包并运行了你提供的例子，和你描述的一样，无法识别，但在在线运行中可以识别。我在zxing库中提交了issue，你可以关注一下。https://github.com/zxing/zxing/issues/1380

**Comment by LeileiCao** [comment]
> 我从最新的zxing库编译javase-3.4.2-jar-with-dependencies.jar包并运行了你提供的例子，和你描述的一样，无法识别，但在在线运行中可以识别。我在zxing库中提交了issue，你可以关注一下。[zxing/zxing#1380](https://github.com/zxing/zxing/issues/1380)
好的，谢谢。

**Comment by ChenjieXu** [comment]
Good evening, your issue has been resolved in release v1.0.0, please install the latest version of pyzxing. Thank you for your use and feedback~

**Comment by LeileiCao** [comment]
> 您好，您提的问题已经在release v1.0.0中解决，请您安装最新版本的pyzxing。感谢您的使用和反馈~
> 
> Good evening, your issue has been resolved in release v1.0.0, please install the latest version of pyzxing. Thank you for your use and feedback~

Thank you.
