### ISSUE TITLE
Which visual codes types are supported? 

### ISSUE THREAD

**Issue by MistyDi** [ChenjieXu/pyzxing#24]
Which visual codes types are supported to be decoded with the pyzxing wrapper?
Is working with DataMatrix types available, for example?

**Comment by ChenjieXu** [comment]
These format are supported referred to zxing github page.

1D product | 1D industrial | 2D
-- | -- | --
UPC-A | Code 39 | QR Code
UPC-E | Code 93 | Data Matrix
EAN-8 | Code 128 | Aztec
EAN-13 | Codabar | PDF 417
UPC/EAN Extension 2/5 | ITF | MaxiCode
  |   | RSS-14
  |   | RSS-Expanded

</html>
