### ISSUE TITLE
 No barcode found

### ISSUE THREAD

**Issue by TyrionChou** [ChenjieXu/pyzxing#25]
hi there, why this image detection failed? this picture is quite clear!
![1152](https://user-images.githubusercontent.com/25079938/123101572-c910b480-d466-11eb-8d7b-fec499058351.jpg)

**Comment by TyrionChou** [comment]
change parameter --multi to --pure_barcode

**Comment by ChenjieXu** [comment]
Thank you for the issue. It is a good feature to add into my code. I will add it as a parameter.
