### ISSUE TITLE
M1 mac电脑无法使用arm版本jdk，x86jdk可以使用，但是太慢了

### ISSUE THREAD

**Issue by yangqingbin** [ChenjieXu/pyzxing#27]
![image](https://user-images.githubusercontent.com/39461869/125221564-f54b8280-e2fa-11eb-90a9-71ec731c44fa.png)
arm 8.0版本jdk报错，如图所示，x86v版本8.0jdk正常，但是运行速度太慢了

**Comment by ChenjieXu** [comment]
您可以尝试自己编译zxing库

**Comment by ChenjieXu** [comment]
长时间未回复，如果你有任何问题，可以随时打开这个issue
