### ISSUE TITLE
How to interpret points in result dictionary?

### ISSUE THREAD

**Issue by alinasrullayev** [ChenjieXu/pyzxing#28]
Hello i have simple but annoying question that i couldn't found answer for. I got result in a form like `'{filename': ''filename.jpg, 'format': b'QR_CODE', 'type': b'URI', 'raw': b'raw_data', 'parsed': b'parsed_data', 'points': [(435.0, 378.5), (433.0, 271.0), (545.5, 267.66666), (527.25, 359.5)]}`

I need to draw border around found barcode so how do i know what these numbers inside 'points' list means?

**Comment by ChenjieXu** [comment]
You may use cv2.drawContours() to draw to draw the polygon

**Comment by alinasrullayev** [comment]
> You may use cv2.drawContours() to draw to draw the 

Thanks for the reply! Yes I've tried many times to actually figure it out that what is the relationship between the points from result and the given input image. Then i realized that the points are actually pointing the sides of the QR code. After that i just created little boxes where the points indicate.

**Comment by ChenjieXu** [comment]
I'm glad to know this problem was solved.
