### ISSUE TITLE
批量识别速度太慢

### ISSUE THREAD

**Issue by xulihang** [ChenjieXu/pyzxing#29]
识别一张图片要1秒，而zbar是150毫秒。我看了下代码，是不是每次识别不同的图片都要重新用java -jar运行zxing，这样每次重新加载下zxing会影响速度。是不是可以建一个zxing的进程，然后和这个进程通讯（比如用zeromq）来解码。

**Comment by ChenjieXu** [comment]
您说的很对，感谢反馈！
我用的方法是简单地通过命令行调用jar包，建立zxing进程可能需要python建立java 虚拟机进程进行并与之通讯的技术，这方面我暂时还没有思路，我可能还需要一定的时间。

**Comment by ChenjieXu** [comment]
还有一种可能就是zbar使用的应该是C语言，在速度上应该是比zxing的java有很大的优势的

**Comment by ChenjieXu** [comment]
因为我使用的语言是Python，所以可能暂时不会考虑使用其他语言。
