### ISSUE TITLE
How to get detected codewords before error correction?

### ISSUE THREAD

**Issue by prnvjb** [ChenjieXu/pyzxing#3]
Hi,
I'm working on code-words error correction algorithm as part of my thesis. I need to show a demo but didn't find any good pure python qrcode reader and my understanding with this library is limited. I just want to quickly know how to get detected code words. Can somebody point me in this library to get detected codewords, preferably as an array, before feeding them for error correction.
Thanks!

**Comment by ChenjieXu** [comment]
This repository is just a python wrapper of a java qrcode reader and does not have any code related to qrcode decoding. There are two popular qrcode reader module, zxing and zbar, but none of them are written in python. There is also a qrcode detection function in opencv4. You may find some useful information in those source codes.

**Comment by ChenjieXu** [comment]
If you have anything to discuss, please let me know. I'll reopen this issue.
