### ISSUE TITLE
性能不如微信

### ISSUE THREAD

**Issue by lidh15** [ChenjieXu/pyzxing#30]
有的二维码微信可以识别但是用pyzxing识别不出来，这样下去什么时候能打破鹅厂的垄断，客户很不满，让我来发issue，理解一下

**Comment by ChenjieXu** [comment]
pyzxing是zxing的python封装，识别效果的话可能还是要去zxing库去反应。
开源算法和收费软件的效果肯定是不能比的，肯定有收费软件效果是比微信好的，总不能又想免费又要效果行业顶尖，是吧？

**Comment by funchan24** [comment]
@lidh15 可以尝试调整图片大小，比如将图片短边缩放到512像素，尝试识别，不行再缩放到1024像素，这样能提高识别成功率。

**Comment by cumthxy** [comment]
> 

你是不是伞兵啊。你用免费的，自己不会优化。卖给客户 ，人家不满意你还来这里提出不满意？伞兵一个。

**Comment by TingFeng-7** [comment]
> @lidh15 可以尝试调整图片大小，比如将图片短边缩放到512像素，尝试识别，不行再缩放到1024像素，这样能提高识别成功率。

感谢~ 好使
